---
title: "Visualização - IDEB"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    runtime: shiny
    theme: flatly
---

```{r setup, include=FALSE}
suppressPackageStartupMessages({
  library(flexdashboard)
  library(readxl)
  library(dplyr)
  library(ggplot2)
  library(plotly)
  library(maps)
  library(brazilmaps)
  library(highcharter) #talvez se um de nós souber como usar 
  library(stringr)
  library(viridis)
})
```


```{r global, include = FALSE}
br <- read_excel("br_tidy.xlsx")
estados <- read_excel("estados_tidy.xlsx")
#censo <- read_excel
estados$UF <- str_replace_all(estados$UF, "M. G.", "Mato Grosso") %>% 
  str_replace_all("R. G.", "Rio Grande") %>%
  str_to_upper() #P poder dar o join com o mapa sem precisar do código do estado
#cod_ufs <- read_excel("Codigos_ufs.xlsx") #talvez nem precisemos
estados %>% mutate(Regiao = str_replace_all(Regiao, "SU","S") %>%
                     str_replace_all("NO","N")) -> estados
```

Escala Estadual
=====================================

Column{.sidebar}
-----------------------------------------------------------------------

  Painel para a seleção do Nível de escolaridade, Dependência admnistrativa e Ano dejados:

```{r}
# Talvez oferecer escolha de nível escolar e rede de ensino
selectInput("nivelescolaridade",
            label = "Nível de Ensino",
            choices = c("Fundamental anos iniciais" = "EFI",
                        "Fundamental anos finais" = "EFF",
                        "Ensido médio" = "EM"),
            selected = "EFI")
selectInput("rede",
            "Rede de Ensino",
            choices = c("Pública" = "Estadual",
                        "Privada" = "Privada",
                        "Total" = "Total"),
            selected = "Total")
# sliderInput(inputId = "ano",
#             label = "Ano",
#             min = 2005,
#             max = 2017,
#             value = 2011,
#             step = 2)
selectInput("ano",
            label = "Ano",
            choices = seq(2005, 2017, by = 2),
            selected = "2011")
```

Row {data-width=500}
-----------------------------------------------------------------------

### IDEB para os estados

```{r}
selected_data <- reactive({
  aaa <- get_brmap(geo = "State") %>% 
    left_join(estados, by = c("nome" = "UF")) %>%
    filter(NivelEscolaridade == input$nivelescolaridade, 
           Ano == input$ano,
           Rede == input$rede) %>%
    mutate(hover = paste("UF:", nome, '<br>','ideb: ',IDEB))
  
  aaa
  })
# Com as chaves eu posso escrever expressões aqui e no final retornar algo
output$mapaestados <- renderPlotly({
  
  selected_data() %>% 
    ggplot() +
    geom_sf(aes(fill = IDEB, text = hover)) +
    scale_fill_viridis_c(direction = -1, limits = c(2,8),option = "C") -> p
  
  g <- ggplotly(p)
  
  #build <- plotly_build(g)
  
  #build$data[[1]]$text <- paste0('UF: ', selected_data()$UF, '<br>', 
  #                               'IDEB: ', as.character(round(selected_data()$IDEB,
   #                                                           2))) 
  
  #build
   
  
  # g %>%
  #   add_trace(
  #     z = ~IDEB,
  #     text =  ~hover,
  #     locations = ~geometry,
  #     hoverinfo = 'text',
  #     marker = list(color='green')) -> g
  g
  
})
plotlyOutput("mapaestados")
```


Row {data-width=500}
-----------------------------------------------------------------------

### Desempenho escolar por Taxa de Aprovação para os estados
```{r}
dados_selecionados <- reactive({
  aab <- estados %>%
    filter(NivelEscolaridade == input$nivelescolaridade, 
           Ano == input$ano,
           Rede == input$rede) #%>%
    #mutate(hover = paste("UF:", nome, '<br>','ideb: ',IDEB))
  
  aab
  })
# Com as chaves eu posso escrever expressões aqui e no final retornar algo
output$teste1 <- renderPlotly({
  
  dados_selecionados() %>% 
    ggplot() +
    geom_point(aes(x = N, y = P,
                   size = IDEB, fill = UF), show.legend = FALSE) +
    #scale_x_continuous(limits = c(0, 10)) +
    #scale_y_continuous(limits = c(0, 1)) +
    xlab("Nota média padronizada") +
    ylab("Taxa de Aprovação") -> p
  
  g <- ggplotly(p)
  
  #build <- plotly_build(g)
  
  #build$data[[1]]$text <- paste0('UF: ', selected_data()$UF, '<br>', 
  #                               'IDEB: ', as.character(round(selected_data()$IDEB,
   #                                                           2))) 
  
  #build
   
  
  # g %>%
  #   add_trace(
  #     z = ~IDEB,
  #     text =  ~hover,
  #     locations = ~geometry,
  #     hoverinfo = 'text',
  #     marker = list(color='green')) -> g
  g
  
})
plotlyOutput("teste1")
```




Escala Regional
=====================================

### Violinos do IDEB dentro de cada região
```{r}
# estados %>% 
#   filter(ensino %in% c("Público", "Privado")) %>% 
#   ggplot(aes(x = NivelEscolaridade, y = IDEB)) +
#   geom_boxplot() +
#   facet_wrap(~ensino) -> p
# 
# p
p <- estados %>%
  filter(Rede == "Total") %>%
  plot_ly(
    x = ~Regiao,
    y = ~IDEB,
    split = ~Regiao,
    type = 'violin',
    box = list(
      visible = T
    ),
    meanline = list(
      visible = T
    )
  )
p
```






Escala Nacional
=====================================


Column{.sidebar}
-----------------------------------------------------------------------

  Seleção do nível de ensino e dependência admnistrativa:

```{r}
# Talvez oferecer escolha de nível escolar e rede de ensino
selectInput("nivelescolaridadebr",
            label = "Nível de Ensino",
            choices = c("Fundamental anos iniciais" = "EFI",
                        "Fundamental anos finais" = "EFF",
                        "Ensido médio" = "EM"),
            selected = "EFI")
selectInput("redebr",
            "Rede de Ensino",
            choices = c("Pública" = "Estadual",
                        "Privada" = "Privada",
                        "Total" = "Total"),
            selected = "Total")
# sliderInput(inputId = "ano",
#             label = "Ano",
#             min = 2005,
#             max = 2017,
#             value = 2011,
#             step = 2)
```


Row {data-width=500}
-----------------------------------------------------------------------


### IDEB

```{r}
sel_data <- reactive({
 
    aad <- br %>%
    filter(NivelEscolaridade == input$nivelescolaridadebr,
           Rede == input$redebr) 
  
  aad
  })
# Com as chaves eu posso escrever expressões aqui e no final retornar algo
output$teste2 <- renderPlotly({
  
  sel_data() %>% 
    ggplot(aes(x = Ano)) +
    geom_line(aes(y = IDEB, group = Rede)) +
    geom_line(aes(y = Proj, group = Rede), linetype = "dashed") +
    ylab("IDEB e Projeção")-> p
  
  g <- ggplotly(p)
  
  #build <- plotly_build(g)
  
  #build$data[[1]]$text <- paste0('UF: ', selected_data()$UF, '<br>', 
  #                               'IDEB: ', as.character(round(selected_data()$IDEB,
   #                                                           2))) 
  
  #build
   
  
  # g %>%
  #   add_trace(
  #     z = ~IDEB,
  #     text =  ~hover,
  #     locations = ~geometry,
  #     hoverinfo = 'text',
  #     marker = list(color='green')) -> g
  g
  
})
plotlyOutput("teste2")
```



### Densidades do IDEB para as redes ao longo dos anos

```{r}
  estados %>%
  filter(Rede %in% c("Pública", "Privada")) %>% 
  ggplot(aes(x = IDEB, y = ..density.., fill = Ano)) +
  geom_density() +
  ylab("Densidade") +
  facet_wrap(~Rede) + 
  theme_classic()  -> p
  
  g <- ggplotly(p)
  
  
  g
  
```
